### ISSUE TITLE
java 12 is not working

### ISSUE THREAD

**Issue by nedijahij** [fwcd/KotlinLanguageServer#114] opened 2019-06-21 09:43 UTC
After clone the project, then I execute: 
```
cd KotlinLanguageServer/
./gradlew server:build
```

And then error output as following: 
```
Downloading https://services.gradle.org/distributions/gradle-4.6-bin.zip
......................................................................
Unzipping /home/yourpc/.gradle/wrapper/dists/gradle-4.6-bin/4jp4stjndanmxuerzfseyb6wo/gradle-4.6-bin.zip to /home/yourpc/.gradle/wrapper/dists/gradle-4.6-bin/4jp4stjndanmxuerzfseyb6wo
Set executable permissions for: /home/yourpc/.gradle/wrapper/dists/gradle-4.6-bin/4jp4stjndanmxuerzfseyb6wo/gradle-4.6/bin/gradle

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '12.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
[yourpc@yourpc KotlinLanguageServer]$ ./gradlew server:build

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '12.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
[yourpc@yourpc KotlinLanguageServer]$ ./gradlew server:run

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '12.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by fwcd** [comment] 2019-06-24 21:13
Duplicate of #108, Java 11+ support will be coming soon in #109.

**Closed by fwcd** 2019-06-24 21:13 UTC
Labels: duplicate
