### ISSUE TITLE
Autocompletion and error detecting problem

### ISSUE THREAD

**Issue by minkir014** [fwcd/KotlinLanguageServer#93] opened 2019-03-17 20:49 UTC
The extension shows error on somethings that mustn't be error like
![Screenshot (2)](https://user-images.githubusercontent.com/42807112/54497691-7995c280-4906-11e9-9b74-60e99c873103.png)
Although an error disappears when importing java.lang
![Screenshot (1)](https://user-images.githubusercontent.com/42807112/54497701-8ca89280-4906-11e9-9612-c5b2fd12ebfe.png)
but it still shows another error of the string array
but in the two cases the compiler understands that and that is the result
![Screenshot (3)](https://user-images.githubusercontent.com/42807112/54497729-d6917880-4906-11e9-91a6-984ce7cd1109.png)
In addition it isn't autocompleting key words and other things which is highlighted with errors

**Comment by fwcd** [comment] 2019-03-17 20:53
@minkir014 What does the compiler show when you hover over the first `println` error?

**Comment by minkir014** [comment] 2019-03-17 21:53
The compiler doesn't show errors it prints the output correctly and I'll recommend another issue here that it isn't completing key words or other things that is highlighted with errors like "Array"

**Comment by fwcd** [comment] 2019-03-17 22:21
In the first screenshot there is a red underline. What does the popup show when you hover your mouse over it?

**Comment by minkir014** [comment] 2019-03-18 11:19
It shows this when I hover over printlin
![Screenshot (5)](https://user-images.githubusercontent.com/42807112/54526697-337d4500-4980-11e9-8e70-24c67c8d4fe8.png)


and shows this when I hover over Array
![Screenshot (6)](https://user-images.githubusercontent.com/42807112/54526718-4728ab80-4980-11e9-9c41-4ca9ed0fac6c.png)

and this is an example of not completing key words
![Screenshot (4)](https://user-images.githubusercontent.com/42807112/54526748-64f61080-4980-11e9-89c3-cc0faddb0c98.png)

**Comment by fwcd** [comment] 2019-03-18 12:27
Might be a duplicate of #73, #51 and #58.

How is your project configured? Do you use Maven or Gradle?

**Comment by minkir014** [comment] 2019-03-18 15:16
In this example, this is a single file not a project I wanted to check the extension. Should I use gradle or maven?

**Comment by fwcd** [comment] 2019-03-18 15:26
I have splitted up this issue into #95 and #96 to address the individual requests.

**Closed by fwcd** 2019-03-18 15:26 UTC
Labels: bug, code completion, diagnostics

**Comment by fwcd** [comment] 2019-03-18 15:28
Outside of projects, the extension currently tries to find the standard library in either your local Maven or Gradle repository. This, however, requires you to have previously worked with Maven/Gradle projects using Kotlin.

By the way, if you need a sample project that uses Gradle, see [KotlinQuickStart](https://github.com/fwcd/KotlinQuickStart).

**Comment by minkir014** [comment] 2019-03-19 12:54
Thanks for this I started with maven project and kotlin every thing worked correctly completing packages and methods and properties but the debugger didn't find my main class.What should I do to make it work

**Comment by fwcd** [comment] 2019-03-20 02:08
@minkir014 This belongs into https://github.com/fwcd/KotlinDebugAdapter/issues

**Comment by minkir014** [comment] 2019-03-20 11:58
see this issue https://github.com/fwcd/KotlinDebugAdapter/issues/12

**Comment by Xander1540** [comment] 2024-06-22 03:03
Why can't anyone just tell a straight forward solution to the problem
