### ISSUE TITLE
Please specify proper '-jvm-target' optionkotlin(INLINE_FROM_HIGHER_PLATFORM)

### ISSUE THREAD

**Issue by laibulle** [fwcd/KotlinLanguageServer#72] opened 2018-12-28 02:08 UTC
Trying to use the plugin with java 11 on OSX.
```
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

It is a simple project generate via springr.

I get the following error 

```
Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' optionkotlin(INLINE_FROM_HIGHER_PLATFORM)
```
<img width="589" alt="screenshot 2018-12-28 at 03 05 39" src="https://user-images.githubusercontent.com/2327626/50499884-78fb3780-0a4d-11e9-8762-eabc268b1dc8.png">

You can reproduce using this repo https://github.com/laibulle/spring-kotlin-sample. The code run via 
```
gradle bootRun
```

Best regards

**Comment by laibulle** [comment] 2018-12-28 20:21
I switch back to Java 8

```
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
```

and still have the same message.

**Comment by kenpb** [comment] 2019-05-28 04:11
Same problem here, setting the `kotlin.compiler.jvmtarget` in maven or the `jvmTarget` in gradle have no effect whatsoever.

```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by pcgeek86** [comment] 2019-07-03 18:40
I'm having this same issue. Could you add a VSCode setting to change the version of the `jvmTarget` attribute? My `build.gradle.kts` file is set to use the correct `jvmTarget`, but the Kotlin language server doesn't respect this value.

Here's the relevant portion of my Gradle configuration:

```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

tasks.withType<KotlinCompile> {
    kotlinOptions.suppressWarnings = true
    kotlinOptions.jvmTarget = JavaVersion.VERSION_1_8.toString()
}
```

The specific error I'm getting is a little different than others, but the root cause is similar.

> Calls to static methods in Java interfaces are prohibited in JVM target 1.6. Recompile with '-jvm-target 1.8'kotlin(INTERFACE_STATIC_METHOD_CALL_FROM_JAVA6_TARGET_ERROR)

<img width="1123" alt="Screen Shot 2019-07-03 at 11 37 39 AM" src="https://user-images.githubusercontent.com/466713/60616761-0fa30b00-9d87-11e9-8b1b-a37db8d3ee8e.png">

**Comment by mcraveiro** [comment] 2019-07-17 08:34
I've bumped into this problem. Is there some kind of "brute force" approach to solve this problem? For example, force KLS to always use 1.8. This would be sufficient for my purposes for now since I am using the same Java version on all my projects.

**Comment by kuro46** [comment] 2019-07-18 09:04
I have same problem too.  
And I created a patch that forcely set `jvm-target` to `1.8`. It works well :)

```patch
diff --git a/server/src/main/kotlin/org/javacs/kt/Compiler.kt b/server/src/main/kotlin/org/javacs/kt/Compiler.kt
index 0f223df..e310b90 100644
--- a/server/src/main/kotlin/org/javacs/kt/Compiler.kt
+++ b/server/src/main/kotlin/org/javacs/kt/Compiler.kt
@@ -16,6 +16,7 @@ import org.jetbrains.kotlin.cli.jvm.config.addJvmClasspathRoots
 import org.jetbrains.kotlin.config.CommonConfigurationKeys
 import org.jetbrains.kotlin.config.CompilerConfiguration
 import org.jetbrains.kotlin.config.JVMConfigurationKeys
+import org.jetbrains.kotlin.config.JvmTarget
 import org.jetbrains.kotlin.container.ComponentProvider
 import org.jetbrains.kotlin.container.get
 import org.jetbrains.kotlin.idea.KotlinLanguage
@@ -49,6 +50,7 @@ class Compiler(classPath: Set<Path>) {
     private val config = CompilerConfiguration().apply {
         put(CommonConfigurationKeys.MODULE_NAME, JvmAbi.DEFAULT_MODULE_NAME)
         put(CLIConfigurationKeys.MESSAGE_COLLECTOR_KEY, LoggingMessageCollector)
+        put(JVMConfigurationKeys.JVM_TARGET, JvmTarget.JVM_1_8)
         addJvmClasspathRoots(classPath.map { it.toFile() })
     }
     val environment: KotlinCoreEnvironment
```

**Comment by mcraveiro** [comment] 2019-07-18 09:19
Genius! thanks @kuro46, applying the patch locally as we speak :-)

**Comment by mcraveiro** [comment] 2019-07-18 09:33
Applied, works as advertised! :-) Thanks very much!

**Comment by fwcd** [comment] 2019-07-18 10:44
@kuro46 Thank you very much, I will add this as a configuration option to the language server!

**Comment by fwcd** [comment] 2019-07-18 16:41
Fixed by #128.

**Closed by fwcd** 2019-07-18 16:41 UTC
Labels: bug

**Comment by mcraveiro** [comment] 2019-07-18 16:47
Wow that was fast! :-) bit of a newbie question, where do I place the new config option ``` kotlin.compiler.jvm.targe```? TIA

**Comment by fwcd** [comment] 2019-07-18 16:50
@mcraveiro LSP has a `workspace/didChangeConfiguration` method for this, not sure how this is implemented on the Emacs side though.

**Comment by mcraveiro** [comment] 2019-07-18 16:51
Aha, excellent - I'll dig through the lisp. Cheers

**Comment by fwcd** [comment] 2019-07-18 16:53
To add to this, this is a sample configuration taken from my current setup:

```
{"kotlin":{"languageServer":{"enabled":true},"compiler":{"jvm":{"target":"1.8"}},"linting":{"debounceTime":250},"completion":{"snippets":{"enabled":true}},"debounceTime":250,"snippetsEnabled":true}}
```

This object is passed as part of the [`DidChangeConfigurationParams`](https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration):

```typescript
interface DidChangeConfigurationParams {
	/**
	 * The actual changed settings
	 */
	settings: any;
}
```

**Comment by ahmadmu** [comment] 2019-11-26 12:41
How can I change the target in a maven project in vscode? I'm getting the same error.

**Comment by justinhj** [comment] 2021-05-14 23:32
Having some trouble making this work with Neovim. 

In my Kotlin project I have set the JVM target to 1.8 

```
tasks.withType<KotlinCompile>() {
    kotlinOptions.jvmTarget = "1.8"
}
```

and also patched the lsp code as follows

```
diff --git a/server/src/main/kotlin/org/javacs/kt/compiler/Compiler.kt b/server/src/main/kotlin/org/javacs/kt/compiler/Compiler.kt
index ddb1aff..4051d72 100644
--- a/server/src/main/kotlin/org/javacs/kt/compiler/Compiler.kt
+++ b/server/src/main/kotlin/org/javacs/kt/compiler/Compiler.kt
@@ -116,6 +116,7 @@ private class CompilationEnvironment(
                 put(CommonConfigurationKeys.MODULE_NAME, JvmProtoBufUtil.DEFAULT_MODULE_NAME)
                 put(CommonConfigurationKeys.LANGUAGE_VERSION_SETTINGS, languageVersionSettings)
                 put(CLIConfigurationKeys.MESSAGE_COLLECTOR_KEY, LoggingMessageCollector)
+                               put(JVMConfigurationKeys.JVM_TARGET, JvmTarget.JVM_1_8)
                 add(ComponentRegistrar.PLUGIN_COMPONENT_REGISTRARS, ScriptingCompilerConfigurationComponentRegistrar())
 
                 addJvmClasspathRoots(classPath.map { it.toFile() })
diff --git a/server/src/test/resources/kotlinDSLWorkspace/build.gradle.kts b/server/src/test/resources/kotlinDSLWorkspace/build.gradle.kts
index 2f30179..01a7734 100644
--- a/server/src/test/resources/kotlinDSLWorkspace/build.gradle.kts
+++ b/server/src/test/resources/kotlinDSLWorkspace/build.gradle.kts
@@ -7,3 +7,11 @@ plugins {
 repositories {
     jcenter()
 }
+
+tasks.withType<KotlinCompile> {
+    kotlinOptions {
+        jvmTarget = "1.8"
+    }
+
+    dependsOn(":util:createVersionFile")
+}
```

And I still get the described in the issue title. I'm not really sure what I'm fixing. Maybe when I configure the lsp server in Neovim I need to set the Kotlin target there?

**Comment by lazebny** [comment] 2024-05-19 15:01
`vim` + `vim-lsp` fixed with adding workspace config:
```vim
let g:lsp_settings = {
\  'kotlin-language-server': {
\    'workspace_config': {
\      'kotlin': {'compiler': {'jvm': {'target': '17'}}}
\    }
\  }
\}
```

**Comment by jeusdi** [comment] 2024-06-12 09:18
I'm getting same issue.
I'm using a fresh lazyvim kotlin language server. You can see [default configuration here](https://www.lazyvim.org/extras/lang/kotlin).

It's not clear to where should I override jvm-target setting.

I guess I should need to create an additional config file...

Any ideas?

**Comment by bdogabriel** [comment] 2025-03-15 07:31
I am getting this issue in vscode. First I thought my build.gradle.kts was wrong. But then I installed the Intellij IDE and the error does not show there.

I am using jvm 21 and I also tried using jvm 17, but it didn't work. Do I need to use specifically jvm 1.8?

I don't know if I am doing something wrong related to the vscode configuration, if someone have any ideas, I would appretiate the help.

my build.gradle.kts file:
```
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
	kotlin("jvm") version "2.1.10"
	kotlin("plugin.spring") version "2.1.10"
	id("org.springframework.boot") version "3.4.3"
	id("io.spring.dependency-management") version "1.1.7"
}

group = "com.mercadolivro"
version = "0.0.1-SNAPSHOT"

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-web")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
	testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
	testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

kotlin {
	compilerOptions {
		freeCompilerArgs.addAll("-Xjsr305=strict")
		jvmTarget.set(JvmTarget.JVM_21)
	}
}

tasks.withType<Test> {
	useJUnitPlatform()
}
```

The error:
![Image](https://github.com/user-attachments/assets/125de4cb-46ab-4cde-91a5-de65830554e6)

**Comment by HanCheo** [comment] 2025-04-03 12:05
Modified the kotlin compiler part of the vscode settings to the correct version.
it work for me

<img width="960" alt="Image" src="https://github.com/user-attachments/assets/65f03a0a-a4f9-4469-94c5-5c10d9f9054c" />

**Comment by bdogabriel** [comment] 2025-04-28 02:54
@HanCheo thanks for the answer! I didn't try this, though, because I ended up switching my workflow to Neovim.
