### ISSUE TITLE
Java and Kotlin cannot refer to each other

### ISSUE THREAD

**Issue by weifuchuan** [fwcd/KotlinLanguageServer#25] opened 2018-06-22 05:20 UTC
Now, I have a project in which some class of Java import some class of Kotlin and some class of Kotlin import some class of Java. It not work. There are many errors and red line on screen. 
And I try to "Go to definition" which is a class by downloading in maven, which in kotlin class, not successed. 

How can I resolve it?

**Comment by fwcd** [comment] 2018-06-22 07:19
Duplicate of #4

**Closed by fwcd** 2018-06-22 07:19 UTC
